var resData = {
  "groups":[
    {
      "keys":"ym-logo_png,angle_png,avatar-bg_png,b1_png,b2_png,b3_png,b4_png,b5_png,b6_png,b7_png,b8_png,circle1_png,circle2_png,circle3_png,circle4_png,circle5_png,index-bg_png,index-subject_png,index-title_png,main-bg_png,meteor1_png,meteor2_png,meteor3_png,meteor4_png,page-arrow_png,qrcode_jpg,redpr_png,redps_png,roof-bg_png,shareMask_png,stars_png,thanks-title_png,title-frame_png",
      "name":"preload"
    }],
  "resources":[
    {
      "name":"ym-logo_png",
      "type":"image",
      "url":"ym-logo.png"
    },
    {
      "name":"angle_png",
      "type":"image",
      "url":"angle.png"
    },
    {
      "name":"avatar-bg_png",
      "type":"image",
      "url":"avatar-bg.png"
    },
    {
      "name":"b1_png",
      "type":"image",
      "url":"b1.png"
    },
    {
      "name":"b2_png",
      "type":"image",
      "url":"b2.png"
    },
    {
      "name":"b3_png",
      "type":"image",
      "url":"b3.png"
    },
    {
      "name":"b4_png",
      "type":"image",
      "url":"b4.png"
    },
    {
      "name":"b5_png",
      "type":"image",
      "url":"b5.png"
    },
    {
      "name":"b6_png",
      "type":"image",
      "url":"b6.png"
    },
    {
      "name":"b7_png",
      "type":"image",
      "url":"b7.png"
    },
    {
      "name":"b8_png",
      "type":"image",
      "url":"b8.png"
    },
    {
      "name":"circle1_png",
      "type":"image",
      "url":"circle1.png"
    },
    {
      "name":"circle2_png",
      "type":"image",
      "url":"circle2.png"
    },
    {
      "name":"circle3_png",
      "type":"image",
      "url":"circle3.png"
    },
    {
      "name":"circle4_png",
      "type":"image",
      "url":"circle4.png"
    },
    {
      "name":"circle5_png",
      "type":"image",
      "url":"circle5.png"
    },
    {
      "name":"index-bg_png",
      "type":"image",
      "url":"index-bg.png"
    },
    {
      "name":"index-subject_png",
      "type":"image",
      "url":"index-subject.png"
    },
    {
      "name":"index-title_png",
      "type":"image",
      "url":"index-title.png"
    },
    {
      "name":"main-bg_png",
      "type":"image",
      "url":"main-bg.png"
    },
    {
      "name":"meteor1_png",
      "type":"image",
      "url":"meteor1.png"
    },
    {
      "name":"meteor2_png",
      "type":"image",
      "url":"meteor2.png"
    },
    {
      "name":"meteor3_png",
      "type":"image",
      "url":"meteor3.png"
    },
    {
      "name":"meteor4_png",
      "type":"image",
      "url":"meteor4.png"
    },
    {
      "name":"page-arrow_png",
      "type":"image",
      "url":"page-arrow.png"
    },
    {
      "name":"qrcode_jpg",
      "type":"image",
      "url":"qrcode.jpg"
    },
    {
      "name":"redpr_png",
      "type":"image",
      "url":"redpr.png"
    },
    {
      "name":"redps_png",
      "type":"image",
      "url":"redps.png"
    },
    {
      "name":"roof-bg_png",
      "type":"image",
      "url":"roof-bg.png"
    },
    {
      "name":"shareMask_png",
      "type":"image",
      "url":"shareMask.png"
    },
    {
      "name":"stars_png",
      "type":"image",
      "url":"stars.png"
    },
    {
      "name":"thanks-title_png",
      "type":"image",
      "url":"thanks-title.png"
    },
    {
      "name":"title-frame_png",
      "type":"image",
      "url":"title-frame.png"
    }]
};